server:
  port: 9527

spring:
  profiles:
    active: dev
  application:
    name: sky-take-out
  datasource:
    username: ${sky.datasource.username}
    password: ${sky.datasource.password}
    driver-class-name: ${sky.datasource.driver-class-name}
    url: ${sky.datasource.url}
  main:
    banner-mode: off
  data:
    redis:
      port: ${sky.redis.port}
      host: ${sky.redis.host}
      password: ${sky.redis.password}
      database: ${sky.redis.database}


mybatis:
  type-aliases-package: com.wh.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    com:
      wh:
        controller: info
        service: info
        mapper: debug

# 项目自定义配置
sky:
  jwt:
    admin-secret-key: ${sky.jwt.admin-secret-key}
    admin-ttl: ${sky.jwt.admin-ttl}
    admin-token-name: ${sky.jwt.admin-token-name}
    user-secret-key: ${sky.jwt.user-secret-key}
    user-ttl: ${sky.jwt.user-ttl}
    user-token-name: ${sky.jwt.user-token-name}
  alioss:
    endpoint: ${sky.alioss.endpoint}
    access-key-id: ${sky.alioss.access-key-id}
    access-key-secret: ${sky.alioss.access-key-secret}
    bucket-name: ${sky.alioss.bucket-name}
  wechat:
    appid: ${sky.wechat.appid}
    secret: ${sky.wechat.secret}
    mchid: ${sky.wechat.mchid}
    mchSerialNo: ${sky.wechat.mchSerialNo}
    privateKeyFilePath: ${sky.wechat.privateKeyFilePath}
    apiV3Key: ${sky.wechat.apiV3Key}
    weChatPayCertFilePath: ${sky.wechat.weChatPayCertFilePath}
    notifyUrl: ${sky.wechat.notifyUrl}
    refundNotifyUrl: ${sky.wechat.refundNotifyUrl}
