server:
  port: 9527


spring:
  application:
    name: sky-take-out
  datasource:
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sky_take_out
  main:
    banner-mode: off


mybatis:
  type-aliases-package: com.wh.entity
  mapper-locations: classpath:mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

# 日志
logging:
  level:
    com:
      wh:
        controller: info
        service: info
        mapper: debug